name: On Pull Request
on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  build:
    if: ${{ github.event.action != 'closed' }}
    uses: nsbno/platform-actions/.github/workflows/build.node.yml@main
    secrets: inherit

  package:
    if: ${{ github.event.action != 'closed' }}
    uses: nsbno/platform-actions/.github/workflows/package.docker.yml@main
    needs:
      - build
    secrets: inherit
    with:
      repo-name: <service-name>
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      artifact-path: ${{ needs.build.outputs.artifact-path }}

  package-s3:
    if: ${{ github.event.action != 'closed' }}
    uses: nsbno/platform-actions/.github/workflows/package.s3-static-files.yml@main
    needs:
      - build
    secrets: inherit
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      service-name: <service-name>

  preview-update:
    if: ${{ github.event.action == 'synchronize' }}
    needs:
      - build
      - package
    uses: nsbno/platform-actions/.github/workflows/deployment.preview.yml@main
    with:
      service-name: <service-name>

  preview-cleanup:
    if: ${{ github.event.action == 'closed' }}
    uses: nsbno/platform-actions/.github/workflows/deployment.preview-cleanup.yml@main
    with:
      service-name: <service-name>
